# Generated by Django 4.2.8 on 2023-12-19 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booksApi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='code_number',
        ),
        migrations.AddField(
            model_name='book',
            name='code',
            field=models.CharField(default='0000', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Author',
        ),
    ]
